// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/submit-assessment.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/submit-assessment.ts
var submit_assessment_default = defineTool({
  name: "submit_assessment",
  title: "Submit Staffing Stability Assessment",
  description: "Save a Staffing Stability Assessment result for the signed-in user. Stores retention/turnover/vacancy metrics, stability score, risk level, and projected financial impact.",
  inputSchema: {
    org_name: z.string().min(1).describe("Organization name"),
    role: z.string().optional().describe("Submitter's role/title at the organization"),
    retention_rate: z.number().min(0).max(100).optional(),
    turnover_rate: z.number().min(0).max(100).optional(),
    vacancy_rate: z.number().min(0).max(100).optional(),
    overtime_pct: z.number().min(0).max(100).optional(),
    stability_score: z.number().min(0).max(100).optional(),
    risk_level: z.enum(["low", "moderate", "high", "severe"]).optional(),
    financial_impact_usd: z.number().min(0).optional().describe("Projected annual financial impact in USD"),
    notes: z.string().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").insert({
      user_id: ctx.getUserId(),
      org_name: input.org_name,
      role: input.role,
      retention_rate: input.retention_rate,
      turnover_rate: input.turnover_rate,
      vacancy_rate: input.vacancy_rate,
      overtime_pct: input.overtime_pct,
      stability_score: input.stability_score,
      risk_level: input.risk_level,
      financial_impact_cents: input.financial_impact_usd ? Math.round(input.financial_impact_usd * 100) : null,
      payload: { notes: input.notes ?? null }
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Assessment saved. id=${data.id}` }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/tools/list-my-assessments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_assessments_default = defineTool2({
  name: "list_my_assessments",
  title: "List my assessments",
  description: "List Staffing Stability Assessments belonging to the signed-in user, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { assessments: data }
    };
  }
});

// src/lib/mcp/tools/get-assessment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_assessment_default = defineTool3({
  name: "get_assessment",
  title: "Get assessment",
  description: "Fetch one Staffing Stability Assessment by id. RLS restricts this to the row owner.",
  inputSchema: {
    id: z3.string().uuid().describe("Assessment id")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/tools/submit-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var submit_lead_default = defineTool4({
  name: "submit_lead",
  title: "Submit lead",
  description: "Record a lead-capture entry (book, consulting, staffing, or general inquiry) tied to the signed-in user.",
  inputSchema: {
    source: z4.enum(["book", "consulting", "staffing", "assessment", "general"]).describe("Which funnel this lead came from"),
    name: z4.string().min(1).optional(),
    email: z4.string().email().optional(),
    org_name: z4.string().optional(),
    role: z4.string().optional().describe("Job title / role"),
    bed_count: z4.number().int().min(0).optional(),
    message: z4.string().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").insert({
      user_id: ctx.getUserId(),
      source: input.source,
      name: input.name,
      email: input.email ?? ctx.getUserEmail() ?? null,
      org_name: input.org_name,
      role: input.role,
      bed_count: input.bed_count,
      message: input.message
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Lead saved. id=${data.id}` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/get-book-info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_book_info_default = defineTool5({
  name: "get_book_info",
  title: "Get book info",
  description: "Return information about 'The Million Dollar Nurse: How Nurse Retention Saves Hospitals Millions and Protects Patient Care' by Kundayi Washaya, RN.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      title: "The Million Dollar Nurse: How Nurse Retention Saves Hospitals Millions and Protects Patient Care",
      author: "Kundayi Washaya, RN",
      audience: "Hospital CFOs, CEOs, CNOs, and healthcare executives",
      themes: [
        "Nurse retention as a financial strategy",
        "Reducing agency reliance",
        "Protecting patient care through workforce stability",
        "Frontline + consulting perspective on staffing ROI"
      ],
      buy_url: "https://seraphyncare.com/book",
      strategy_call_url: "https://calendly.com/seraphyncare-info/30min"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-booking-link.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_booking_link_default = defineTool6({
  name: "get_booking_link",
  title: "Get strategy-call booking link",
  description: "Return the Seraphyn Care free Nurse Retention Strategy Call Calendly link so the user can book a 30-minute call.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const url = "https://calendly.com/seraphyncare-info/30min";
    return {
      content: [
        {
          type: "text",
          text: `Book a free 30-minute Nurse Retention Strategy Call: ${url}`
        }
      ],
      structuredContent: { url, duration_minutes: 30 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "duyxgztajqkyeqihzkvr";
var mcp_default = defineMcp({
  name: "seraphyn-care-mcp",
  title: "Seraphyn Care",
  version: "0.1.0",
  instructions: "Tools for Seraphyn Care \u2014 nurse retention consulting. Save and retrieve Staffing Stability Assessments, submit leads, look up book info, and get the strategy-call booking link. All data tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    submit_assessment_default,
    list_my_assessments_default,
    get_assessment_default,
    submit_lead_default,
    get_book_info_default,
    get_booking_link_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
